def read_file(filename):
    #lire un fichier
    with open(filename, 'r') as f:
        return filename.read()

def write_file(filename, data):
    #ecrire dans  un fichier
    with open(filename, 'w') as f:
        return f.write()
    return 
